### ISSUE TITLE
Organise a bus trip

### ISSUE THREAD

**Issue by bascht** [rubytown/33c3#11]
I talked to @sareg0 yesterday and the Verein could offer to organise bus trips to Hamburg.

So – Random shot:

**Would anyone be interested in going to the congress and back on a bus trip?**
If you are interested, please tell us which town you're coming from. We will then check, if there are enough people from that town interested in a bus trip.

If yes, we should get this sorted / organised in the next two weeks.

**Comment by BriocheBerlin** [comment]
:raising_hand:
Berlin

**Comment by ariaru** [comment]
Berlin as well!

**Comment by bascht** [comment]
Less than 3 weeks to go and it looks like we won't fill a whole bus. 😿 Sorry!
