### ISSUE TITLE
A few members are still without a ticket

### ISSUE THREAD

**Issue by bascht** [rubytown/33c3#7]
So far (as of november 15th)

- [x] @beanieboi
- [x] @twissi

are still without a ticket. This issue could be fixed during one of the next batches on 
`2016-11-19 15:00 (Sa)` or `2016-11-25 10:00 (Fr)`.

**Comment by beanieboi** [comment]
yeah, we already have flights and hotel booked, I hope we can snatch 2 tickets next Saturday.

**Comment by bascht** [comment]
🎆

**Comment by moonglum** [comment]
So we can close the ticket now? 😉
